-- Migración: Agregar columnas de alérgenos a platos

ALTER TABLE platos ADD COLUMN sesamo INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN pescado INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN mariscos INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN apio INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN frutos_secos INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN sulfitos INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN lacteos INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN altramuces INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN gluten INTEGER DEFAULT 0;
ALTER TABLE platos ADD COLUMN ovoproductos INTEGER DEFAULT 0;
